import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const neoneon = localFont({
  src: [
    {
      path: "public/fonts/Neoneon.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Neoneon.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-neoneon", // Creates a CSS variable for Tailwind
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${neoneon.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
